name: Create Release Zip

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Zip source code
      run: zip -r latest.zip .
      
    - name: Upload release artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-artifact
        path: latest.zip
